FROM maven:3.9.6-sapmachine-21 AS build
COPY . /app
WORKDIR /app/api
COPY ./api/src/main/resources/application.prod.yaml src/main/resources/application.yaml
RUN mvn clean
RUN mvn package -DskipTests

FROM openjdk:17
COPY --from=build app/api/target/api-0.0.1.jar /api.jar
EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "/api.jar" ]