version: '3'

services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=aquila

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - 8025:8025

  aquila_api:
    image: manishdait/aquila_api:0.0.1 
    container_name: aquila_api
    ports:
      - 8080:8080
    depends_on:
      mysql_db:
        condition: service_started
      mailhog:
        condition: service_started
    restart: always

  aquila_client:
    image: manishdait/aquila_client:0.0.1 
    container_name: aquila_client
    ports:
      - 8090:80
    depends_on:
      - aquila_api
    restart: always
    

volumes:
  data: {}
