FROM node:alpine AS build
COPY ./client/aquila-ui /app
WORKDIR /app
RUN npm install -g @angular/cli
RUN npm install
RUN ng build

FROM nginx
COPY --from=build /app/dist/aquila-ui/browser /usr/share/nginx/html
COPY ./client/aquila-ui/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

