spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/latte_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:password}
  flyway:
    user: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:password}