server:
  port:  8080
  
spring:
  profiles:
    active:
    - dev
  application:
    name: latte-api
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0

security:
  jwt:
    secret-key: 815F1298534CA2989B84C1C2F48D4609E7A05811E0700653661466A6
    expiration: 100000
  refresh-token:
    expiration: 604800