spring:
  datasource:
    url: jdbc:mysql://mysql_db:3306/aquila
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: update

    show-sql: true

  mail:
    host: mailhog
    port: 1025

app:
  default:
    username: Admin
    password: Password
    email: admin101@aquila.demo